### ISSUE TITLE
Crash in rtr_mgr_conf_in_sync()

### ISSUE THREAD

**Issue by ton31337** [rtrlib/rtrlib#275]
### Description
```
(gdb) bt
#0  raise (sig=sig@entry=11) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f636a27d18d in core_handler (signo=11, siginfo=0x7ffd0b6018f0, context=<optimized out>)
    at lib/sigevent.c:262
#2  <signal handler called>
#3  0x00007f6369c68c23 in rtr_mgr_conf_in_sync () from /lib/x86_64-linux-gnu/librtr.so.0
#4  0x00007f6369c84320 in start_expired (thread=<optimized out>) at bgpd/bgp_rpki.c:601
#5  0x00007f636a28e323 in thread_call (thread=thread@entry=0x7ffd0b601e70) at lib/thread.c:2002
#6  0x00007f636a24b450 in frr_run (master=0x5555efe20660) at lib/libfrr.c:1196
#7  0x00005555ee7522bc in main (argc=<optimized out>, argv=<optimized out>) at bgpd/bgp_main.c:519
(gdb) frame 3
#3  0x00007f6369c68c23 in rtr_mgr_conf_in_sync () from /lib/x86_64-linux-gnu/librtr.so.0
(gdb) frame 4
#4  0x00007f6369c84320 in start_expired (thread=<optimized out>) at bgpd/bgp_rpki.c:601
warning: Source file is more recent than executable.
601		if (!rtr_mgr_conf_in_sync(rtr_config)) {
(gdb) p *rtr_config
$1 = {groups = 0x5555f04fac40, len = 2, mutex = {__data = {__lock = 1, __count = 0, __owner = 420085, __nusers = 1, 
      __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
    __size = "\001\000\000\000\000\000\000\000\365h\006\000\001", '\000' <repeats 26 times>, __align = 1}, 
  status_fp = 0x7f6369c83940 <rpki_connection_status_cb>, status_fp_data = 0x0, pfx_table = 0x5555f03c8260, 
  spki_table = 0x5555efe9a8f0}
(gdb) 
```

Using this library with FRR (master branch). Replicate:

```
rpki
  rpki polling_period 7200
  rpki cache 192.0.2.1 8080 preference 1
  rpki cache 192.0.2.2 9090 preference 2
  rpki cache 2001:db8::1 1234 preference 3
  rpki cache 2001:db8::2 5678 preference 4
exit

rpki
  no rpki polling_period 
  no rpki cache 192.0.2.1 8080 preference 1
  no rpki cache 192.0.2.2 9090 preference 2
  no rpki cache 2001:db8::1 1234 preference 3
  no rpki cache 2001:db8::2 5678 preference 4
exit
```

### Expected results
Should not crash.

**Comment by mroethke** [comment]
I have so far been unable to reproduce this.
Which rtrlib version are you using and can you provide a backtrace with full debugging info for rtrlib?
